// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnpEFQQvgoLTscDz6BCIgz557D4RotbzA',
    appId: '1:798758941824:web:f4d405b0ca700a72726265',
    messagingSenderId: '798758941824',
    projectId: 'tobeto-new',
    authDomain: 'tobeto-new.firebaseapp.com',
    storageBucket: 'tobeto-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2HrPgtqCfLHnBEYdOweE9nohNc5By5q0',
    appId: '1:798758941824:android:f8b9155801a65ca8726265',
    messagingSenderId: '798758941824',
    projectId: 'tobeto-new',
    storageBucket: 'tobeto-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe-4wPILZ-CTmKc-L7ALvvmvXD3adQaWM',
    appId: '1:798758941824:ios:a608729e0c7c6966726265',
    messagingSenderId: '798758941824',
    projectId: 'tobeto-new',
    storageBucket: 'tobeto-new.appspot.com',
    iosBundleId: 'com.example.tobetoNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe-4wPILZ-CTmKc-L7ALvvmvXD3adQaWM',
    appId: '1:798758941824:ios:23e7b073e629acbc726265',
    messagingSenderId: '798758941824',
    projectId: 'tobeto-new',
    storageBucket: 'tobeto-new.appspot.com',
    iosBundleId: 'com.example.tobetoNew.RunnerTests',
  );
}
